### ISSUE TITLE
Insert Images as background

### ISSUE THREAD

**Issue by OmarGonD** [gadenbuie/xaringanthemer#2]
I was wondering if there is a way to use images (.jpg, .png) as background for a slide? 

I've looked through the code, but couldn't find a function to do that. I remmeber trying to do that with the xaringan package, I succeded but it was a bit tedious to do so....

**Comment by gadenbuie** [comment]
If you want to add a background image to an individual slide, check out the [remarkjs wiki](https://github.com/gnab/remark/wiki) on [setting the per-slide background image](https://github.com/gnab/remark/wiki/Markdown#background-image). Basically,

```markdown
---
background-image: url(image.jpg)
background-position: center
background-repeat: no-repeat
background-size: contain

# Slide with background image
```

where you can modify all the `background-*` CSS lines above the slide content as needed.

Changing the background image for *all* the slides requires modifying the `.remark-slide-content` CSS class, and for this I've included the [template variable](https://pkg.garrickadenbuie.com/xaringanthemer/articles/template-variables.html) `background_image` in xaringanthemer. 

Note that this adds the background image to *all the slides*, so you'd have to set `background-image: none` on any slides that you don't want to have the background. Because the title slide is generated automatically by xaringan, I also included `title_slide_background_image` that you can set to "none" or a different image.
